services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    restart: always
    ports:
      - "5672:5672"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always
    depends_on:
      - rabbitmq