services:
  rabbitmq:
    image: rabbitmq:4.0.4
    ports:
      - "5672:5672"
    healthcheck:
      test: ["executable", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always
    depends_on:
      - rabbitmq